LIME-1259: Added new Happy Path tests for FE E2E tests
govuk-one-login/ipv-cri-kbv-hmrc-api pull request #117
Opened 2024-09-09 12:03 UTC by ChrisBates1

Including coverage of verification score 2 and 0
update step to use verificationScore from the example in the cucumber file added new tests for when 2 questions from 2 questionKeys is supplied Added API tests for malformed response from question endpoint Added cucumber Test Reporting for feature-tests

## Proposed changes

### What changed

Added new Happy Path tests for FE feature-tests
Added cucumber-html-reporter to generate cucumber reports

### Issue tracking

- [LIME-1259](https://govukverify.atlassian.net/browse/LIME-1259)

### Other considerations

[LIME-1259]: https://govukverify.atlassian.net/browse/LIME-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1259]: https://govukverify.atlassian.net/browse/LIME-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-09 12:38 UTC, gds-jbentham commented on feature-tests/jest.config.ts
> +      "./node_modules/jest-html-reporter",
Does this gives the cucumber json file as well I think thats what AWS reads

2024-09-11 13:01 UTC, smsgds requested changes
Needs commits squashed and rebased to pick up the status code changes.

2024-09-12 17:16 UTC, ChrisBates1 commented on feature-tests/tests/resources/step-definitions/post-answer-unhappy-path.step.ts
> +        console.log("ReturnedAnswer = ", postPayload);
Thanks Seamus, i have updated that console log to display the statusCode for all 3 Answer Steps within that test scenario

2024-09-13 15:16 UTC, smsgds approved these changes

2024-09-13 15:23 UTC, merged